name: MeowBot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Build MeowBot
        run: ./gradlew build -x test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Run MeowBot tests
        run: ./gradlew test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ktlint
        run: brew install ktlint
      - name: Run ktlint
        run: ./gradlew ktlintCheck
